import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(Components)/Header/Navbar";
import Footer from "./(Components)/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AmiColo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* Navbar Common to All Pages */}

        <Navbar />

        {/* All the other pages gets displayed here */}
        {children}

        <Footer />
      </body>
    </html>
  );
}
