export const country = [
  { id: 1, nationality: "British" },
  { id: 2, nationality: "Indian" },
  { id: 3, nationality: "French" },
  { id: 4, nationality: "German" },
  { id: 5, nationality: "American" },
  { id: 6, nationality: "Canadian" },
  { id: 7, nationality: "Brazilian" },
  { id: 9, nationality: "Sri Lankan" },
  { id: 10, nationality: "Pakistani" },
  { id: 11, nationality: "Bangladeshi" },
  { id: 12, nationality: "Afghan" },
  { id: 13, nationality: "Ukrainian" },
  { id: 14, nationality: "Chinese" },
  { id: 15, nationality: "Japanese" },
  { id: 16, nationality: "South Korean" },
  { id: 17, nationality: "Saudi Arabian" },
  { id: 18, nationality: "Algerian" },
  { id: 19, nationality: "Moroccan" },
  { id: 20, nationality: "Lebanese" },
  { id: 21, nationality: "Yemeni" },
  { id: 22, nationality: "Turkish" },
  { id: 23, nationality: "Iranian" },
  { id: 24, nationality: "Mexican" },
  { id: 25, nationality: "Spanish" },
  { id: 26, nationality: "United Kingdom" },
  { id: 27, nationality: "United States of America" },
  { id: 28, nationality: "Canada" },
  { id: 29, nationality: "Brazil" },
  { id: 30, nationality: "Others" }, // For all other nationalities
];

export const education = [
  { id: 1, education: "CDI College" },
  { id: 2, education: "Concordia University" },
  { id: 3, education: "Dawson College" },
  { id: 4, education: "École de technologie supérieure (ETS)" },
  { id: 5, education: "École nationale de cirque" },
  { id: 6, education: "HEC Montréal" },
  { id: 7, education: "John Abbott College" },
  { id: 8, education: "LaSalle College" },
  { id: 9, education: "McGill University" },
  { id: 10, education: "Université de Montréal" },
  { id: 11, education: "National Theatre School of Canada" },
  { id: 12, education: "Polytechnique Montréal" },
  { id: 13, education: "Université du Québec à Montréal (UQAM)" },
  { id: 14, education: "Vanier College" },
  { id: 15, education: "Polytechnic School of Montreal" },
  { id: 16, education: "University of Quebec in Montreal" },
  { id: 17, education: "Bishop's University" },
  { id: 18, education: "Other" },
];

